#!/usr/bin/env bash
# Redirection
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
llo="\\\trewrite ^/redirect_me https://media.giphy.com/media/wW95fEq09hOI8/giphy.gif permanent;"
sudo sed -i "42i $llo" /etc/nginx/sites-available/default
sudo service nginx restart
