#!/usr/bin/env bash
# Install my load balancer
FOO="\
frontend load_balancer
    bind *:80
    mode http
    default_backend foo
    
backend foo
    balance roundrobin
    server foo1 35.237.27.173:80 check
    server foo2 35.231.241.190:80 check
"
sudo apt-get -y update
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get install haproxy=1.6.\*
echo "$FOO" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
