#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely,
# and "I am invincible!!!" when receiving a SIGTERM signal.
# trap = Receive and capture signals.
# SIGTERM (15): Kills the process allowing it to finish successfully.
# SIGINT (2): Interrupt with (Ctrl-C).
# SIGQUIT (3): Interrupt with (Ctrl-\).
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
while :
do
    echo To infinity and beyond
    sleep 2
done
