#!/usr/bin/env bash
# Stopped our 4-to_infinity_and_beyond process using ctrl+c.
# kill = Terminates processes based on Process ID number (PID).
# -f = When -f is set, the full command line is used.
kill "$(pgrep -f 4-to_infinity_and_beyond)"
