#!/usr/bin/env bash
# Stops 4-to_infinity_and_beyond process.
# pkill/killall = Terminate running processes based
# on their names and other attributes.
# -f = When -f is set, the full command line is used.
pkill -f 4-to_infinity_and_beyond
