#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely,
# and "I am invincible!!!" when receiving a SIGTERM signal.
# trap = Receive and capture signals.
# SIGTERM (15): Kills the process allowing it to finish successfully.
trap "echo I am invincible!!!" SIGTERM
while :
do
    echo To infinity and beyond
    sleep 2
done
