#!/usr/bin/env bash
# loops from 1 to 10 but with two conditions.
i=1
while [ $i -le 10 ];
do
    if [ $i -eq 4 ];
    then
	echo bad luck
    elif [ $i -eq 8 ];
    then
	echo good luck
    else
	echo Holberton School
    fi
    ((i++))
done
