#!/usr/bin/env bash
# Gives you information about a file.
file="holbertonschool"
if [ -e "$file" ];
then
    echo holbertonschool file exists
    if [ -f "$file" ];
    then
	echo holbertonschool is a regular file
    fi
    if [ -s "$file" ];
    then
	echo holbertonschool file is not empty
    else
	echo holbertonschool file is empty
    fi
else
    echo holbertonschool file does not exist
fi
    
